DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS temperature;
DROP TABLE IF EXISTS swindow;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE swindow (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE temperature (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value REAL NOT NULL
);
